description = "Generic role for basic chats."
prompt = "Assistant"
icon = "sparkles"
accent = "purple"
connection_override_allowed = true
working_directory_override_allowed = true

[[mcps]]
mcp = "internal::Utils"
tools = []
auto_allow_all = true