description = "Generic role for basic chats. No specialized prompt or tools."
prompt = "Assistant"
icon = "sparkles"
accent = "purple"
connection_override_allowed = true
mcps_override_allowed = true

[features]
with_attachments = true
with_response_regen = true
with_chat_trees = true

[utils]
tools = ["calc", "rand", "datetime"]
auto_allow_all = true

[web]
tools = ["web_search", "web_extract"]
auto_allow = ["web_search"]
