description = "A role for editing ICanHazAI configuration. Simply state what you need and the agent will configure the app for you."
prompt = "Configurator"
icon = "gearshape"
connection_override_allowed = true

# this is a special role that uses a special set of tools