description = "Directory-isolated coding agent equipped with all essential tools for code generation and version control."
prompt = "Developer"
icon = "hammer.circle"
accent = "blue"
connection_override_allowed = true
working_directory_override_allowed = true

[utils]
auto_allow_all = true

[filesystem]
auto_allow = ["ls", "read_file", "stat", "pwd"]
directory_isolation = true

[code]
directory_isolation = true
