description = "Directory-isolated coding agent equipped with all essential tools for code generation and version control."
prompt = "Developer"
icon = "hammer.circle"
accent = "blue"
connection_override_allowed = true
working_directory_override_allowed = true

[[mcps]]
mcp = "bundled::Utils"
tools = []
auto_allow_all = true

[[mcps]]
mcp = "bundled::Filesystem"
auto_allow = ["ls", "read_file", "stat"]
directory_isolation = true

[[mcps]]
mcp = "bundled::Code"
directory_isolation = true