// Copyright (C) 2026 Ivan Novohatski <https://d7.wtf/>
// SPDX-License-Identifier: AGPL-3.0-or-later

import Foundation

/// Generates the JSONC text for a connection file created by the wizard.
///
/// The wizard writes the file as plain text so comments are preserved. The
/// parameters the wizard actually collected (`baseUrl`, `apiKey`, `model`,
/// `imageInput`) are written as active JSON keys. A `requestParameters`
/// object with commented-out, provider-specific examples is included so the
/// user knows which advanced options are available.
enum ConnectionFileWriter {

    /// Generates the full JSONC document for a connection.
    /// - Parameters:
    ///   - provider: The connection provider type.
    ///   - baseUrl: The base URL, or nil to omit (provider default).
    ///   - apiKey: The API key, or nil to omit.
    ///   - model: The selected model id (required).
    ///   - imageInput: Whether the model supports image input.
    /// - Returns: A JSONC string with active required params and a commented-out
    ///   `requestParameters` block with provider-specific examples.
    static func generateJSONC(
        provider: ConnectionProvider,
        baseUrl: String?,
        apiKey: String?,
        model: String,
        imageInput: Bool
    ) -> String {
        var output = "// Connection generated by the New Connection wizard.\n"
        output += "// Edit this file to customise advanced options.\n"
        output += "{\n"

        // Omit the commented-out example for Anthropic — it always uses the default endpoint.
        if let baseUrl = baseUrl, !baseUrl.isEmpty {
            output += "    \"baseUrl\": \(jsonString(baseUrl)),\n"
        } else if provider == .openai {
            output += "    // \"baseUrl\": \"https://api.openai.com/v1\",\n"
        }

        if let apiKey = apiKey, !apiKey.isEmpty {
            output += "    \"apiKey\": \(jsonString(apiKey)),\n"
        } else {
            output += "    // \"apiKey\": \"sk-...\",\n"
        }

        output += "    \"model\": \(jsonString(model)),\n"
        output += "    \"imageInput\": \(imageInput),\n"

        output += "\n    // Extra parameters inserted into every request body's root.\n"
        output += "    // Uncomment and edit any of the examples below to enable them.\n"
        output += "    \"requestParameters\": {\n"
        switch provider {
        case .openai:
            output += "        // \"max_completion_tokens\": 1024,\n"
            output += "        // \"temperature\": 1.0,\n"
            output += "        // \"top_p\": 1.0,\n"
            output += "        // \"frequency_penalty\": 0.0,\n"
            output += "        // \"presence_penalty\": 0.0,\n"
            output += "        // \"reasoning_effort\": \"medium\",\n"
            output += "        // \"seed\": 42,\n"
            output += "        // \"thinking\": { \"type\": \"disabled\" }\n"
        case .anthropic:
            output += "        // \"max_tokens\": 4096,\n"
            output += "        // \"temperature\": 1.0,\n"
            output += "        // \"top_p\": 1.0,\n"
            output += "        // \"top_k\": 40,\n"
            output += "        // \"stop_sequences\": [\"\\n\\n\"],\n"
            output += "        // \"thinking\": { \"type\": \"enabled\", \"budget_tokens\": 16000 }\n"
        }
        output += "    }\n"

        output += "}\n"
        return output
    }

    /// Formats a Swift string as a JSON string literal (quoted, with basic
    /// escaping).
    private static func jsonString(_ s: String) -> String {
        return "\"\(escapeString(s))\""
    }

    private static func escapeString(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\")
         .replacingOccurrences(of: "\"", with: "\\\"")
    }
}
