// Copyright (C) 2026 Ivan Novohatski <https://d7.wtf/>
// SPDX-License-Identifier: AGPL-3.0-or-later

import Foundation

/// Generates the TOML text for a connection file created by the wizard.
///
/// `swift-toml` does not preserve comments, so the wizard writes the file as
/// plain text instead of using `TOMLEncoder`. The parameters that the wizard
/// actually collected (model, and endpoint/token when provided) are written
/// uncommented and sorted alphabetically. Every other supported parameter for
/// the connection type is included as a commented-out line with a short
/// description, so the user can enable advanced options by editing the file.
enum ConnectionFileWriter {

    /// A single TOML line: either an active key/value or a commented-out one
    /// with a description.
    private struct Line {
        let key: String
        let value: String?
        let comment: String
        /// Whether this is an active (uncommented) line.
        let active: Bool
    }

    /// Generates the full TOML document for a connection.
    /// - Parameters:
    ///   - provider: The connection provider type.
    ///   - endpoint: The endpoint URL, or nil to omit.
    ///   - token: The API key, or nil to omit.
    ///   - model: The selected model id (required).
    /// - Returns: A TOML string with active required params and commented-out
    ///   optional params.
    static func generateTOML(
        provider: ConnectionProvider,
        endpoint: String?,
        token: String?,
        model: String,
        imageInput: Bool? = nil
    ) -> String {

        // Active (set by the wizard) parameters.
        var active: [(key: String, value: String)] = []
        if let endpoint = endpoint, !endpoint.isEmpty {
            active.append(("endpoint", endpoint))
        }
        if let token = token, !token.isEmpty {
            active.append(("token", token))
        }
        active.append(("model", model))
        if let imageInput = imageInput {
            active.append(("image_input", imageInput ? "true" : "false"))
        }
        // Sort active params alphabetically by key.
        active.sort { $0.key < $1.key }

        // Commented-out optional parameters, grouped by provider.
        let optionalLines: [Line] = optionalParameters(for: provider)

        var output = "# Connection generated by the New Connection wizard.\n"
        output += "# Uncomment and edit any of the options below to enable them.\n\n"

        // Active parameters first, sorted alphabetically.
        for (key, value) in active {
            output += "\(key) = \(tomlValue(value))\n"
        }

        if !optionalLines.isEmpty {
            output += "\n# --- Optional parameters ---\n"
            for line in optionalLines {
                if !line.comment.isEmpty {
                    output += "# \(line.comment)\n"
                }
                if let value = line.value {
                    output += "# \(line.key) = \(value)\n"
                } else {
                    output += "# \(line.key) = \n"
                }
            }
        }

        return output
    }

    /// The commented-out optional parameters for a given provider type.
    private static func optionalParameters(for provider: ConnectionProvider) -> [Line] {
        // Common parameters shared by both provider types.
        var lines: [Line] = [
            Line(key: "image_input", value: "false", comment: "Meta flag: whether the model supports image input.", active: false),
            Line(key: "max_tokens", value: "4096", comment: "Maximum number of tokens to generate.", active: false),
            Line(key: "temperature", value: "1.0", comment: "Sampling temperature (0.0–2.0). Higher is more random.", active: false),
            Line(key: "top_p", value: "1.0", comment: "Nucleus sampling cutoff (0.0–1.0).", active: false),
        ]

        switch provider {
        case .openai:
            lines.append(contentsOf: [
                Line(key: "frequency_penalty", value: "0.0", comment: "Penalize repeated tokens by frequency (-2.0–2.0).", active: false),
                Line(key: "max_completion_tokens", value: "", comment: "Cap on completion tokens (overrides max_tokens on newer models).", active: false),
                Line(key: "presence_penalty", value: "0.0", comment: "Penalize repeated tokens by presence (-2.0–2.0).", active: false),
                Line(key: "reasoning_effort", value: "\"medium\"", comment: "Reasoning effort for reasoning models: none|minimal|low|medium|high.", active: false),
                Line(key: "seed", value: "", comment: "Random seed for deterministic sampling (when supported).", active: false),
                Line(key: "vendor_parameters", value: "\"\"", comment: "Raw JSON string of extra vendor-specific params, e.g. \"{\\\"thinking\\\":{\\\"type\\\":\\\"disabled\\\"}}\".", active: false),
            ])
        case .anthropic:
            lines.append(contentsOf: [
                Line(key: "stop_sequences", value: "[]", comment: "Custom text sequences that stop generation.", active: false),
                Line(key: "thinking_budget", value: "16000", comment: "Token budget for extended thinking (min 1024).", active: false),
                Line(key: "thinking_enabled", value: "false", comment: "Enable Claude extended thinking mode.", active: false),
                Line(key: "top_k", value: "", comment: "Only sample from the top K options at each step.", active: false),
            ])
        }

        // Sort optional lines alphabetically by key.
        return lines.sorted { $0.key < $1.key }
    }

    /// Formats a Swift string as a TOML string value (quoted, with basic
    /// escaping). Non-string values are passed through as-is.
    private static func tomlValue(_ s: String) -> String {
        // Heuristic: if it looks like a number, bool, or array, emit raw.
        let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
        let lower = trimmed.lowercased()
        if lower == "true" || lower == "false" { return lower }
        if trimmed.hasPrefix("[") { return trimmed }
        if let _ = Double(trimmed) { return trimmed }
        // Otherwise treat as a string.
        return "\"\(escapeString(trimmed))\""
    }

    private static func escapeString(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\")
         .replacingOccurrences(of: "\"", with: "\\\"")
    }
}
